# Generated by Django 3.0.3 on 2022-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
