# Generated by Django 4.0.3 on 2022-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_auto_20220326_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
